パフォーマンス改善/詳細検索機能/APIを使用する形に改修
ivis-weko3-dev/weko pull request #198
Opened 2024-02-22 05:35 UTC by Yoshikawa123

改修箇所

- render_templateで渡されている、detail_conditionの処理をコメントアウト
  - modules/weko-records-ui/weko_records_ui/views.py
  - modules/weko-search-ui/weko_search_ui/views.py
  - modules/weko-theme/weko_theme/utils.py

- detail_condition取得用のAPIを追加
  - modules/weko-search-ui/weko_search_ui/views.py

- APIで取得したdetail_conditionを使用する処理に変更
  - modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js

- templateもJSに合わせた処理に変更
  - modules/weko-theme/weko_theme/templates/weko_theme/body_search.html
  - modules/weko-theme/weko_theme/templates/weko_theme/body_search_detail_new.html

2024-02-26 02:14 UTC, ivis-tsukioka requested changes
2023/2/26 9:00~10:00 RV
修正コメントを残しました。対応お願いします。

2024-02-26 07:37 UTC, Yoshikawa123 commented on modules/weko-records-ui/weko_records_ui/views.py
> +    #detail_condition = get_search_detail_keyword('')
残す必要がないため、削除しました。

2024-02-26 07:37 UTC, Yoshikawa123 commented on modules/weko-search-ui/weko_search_ui/views.py
> +    #detail_condition = get_search_detail_keyword("")
残す必要がないため、削除しました。

2024-02-26 07:37 UTC, Yoshikawa123 commented on modules/weko-search-ui/weko_search_ui/views.py
> +            #detail_condition=detail_condition,
残す必要がないため、削除しました。

2024-02-26 07:37 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            $scope.setupInitData = function() {
コメントを追記しました。

2024-02-26 07:38 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            $scope.onClick = function() {
コメントを追記しました。

2024-02-26 07:38 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            $scope.initDataKey = function(){
コメントを追記しました。

2024-02-26 07:39 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +                $scope.setupInitData()
set_current_index_condition関数外の処理であるため、対処しない形とします。

2024-02-26 07:39 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/utils.py
> +    #detail_condition = get_search_detail_keyword('')
残す必要がないため、削除しました。

2024-02-26 07:39 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/utils.py
> +        #detail_condition=detail_condition,
残す必要がないため、削除しました。

2024-02-27 01:54 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +                $scope.setupInitData()
承知した

2024-02-29 00:45 UTC, ivis-tsukioka requested changes
追加コミットを含めRVしました。対応お願いします。

2024-02-29 00:45 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
> +                //if (btn == 'detail-search') {
if (btn == 'detail-search') {　から　} elseをコメントアウトしてコードの非活性化をしてください

2024-02-29 00:45 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
> +                if (false) {
上記と同様の処置をしてください

2024-02-29 00:45 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            // Button to open the detailed search area
$scope.onClick関数自体は開閉というユーザアクションなので、【Button to open/close the detailed search area】が正しいと思われます。
そのうえで、
```
if(!sessionStorage.getItem('init_detail_condition')){
```
下に、『セッションストレージ('init_detail_condition')にデータがある場合、詳細検索条件情報を用意する』などのコメントを残すとよい

2024-02-29 00:45 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            // page init
現在の『initData』関数は以前のものと意味合いが変わっていませんか？
ページの初期化というより、詳細エリアの情報の埋め込み？

2024-02-29 00:45 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            let status_keep_flg = true
このような変数は、上の`$scope.condition_data = [];`が記述されているエリアに書くとよい。
ここに書かないといけない理由が別にあれば教えてください

2024-02-29 01:49 UTC, Yoshikawa123 commented
再レビューの指摘対応を行いました。

確認よろしくお願いします。

2024-02-29 05:38 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            // Button to open the detailed search area
コメントの変更、
「セッションストレージ('init_detail_condition')にデータがない場合、詳細検索情報を用意する」の意味でコメントを追加しました。

2024-02-29 05:40 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            // page init
「詳細検索エリアの情報を生成」を意味するコメントに変更しました。

2024-02-29 05:40 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            let status_keep_flg = true
特に理由はなかったので、指定された箇所で定義しました。

2024-02-29 05:40 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
> +                //if (btn == 'detail-search') {
コメントアウトを行いました。

2024-02-29 05:40 UTC, Yoshikawa123 commented on modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
> +                if (false) {
上記と同様の対応を行いました。

2024-02-29 06:55 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
> +                //if (btn == 'detail-search') {
OK

2024-02-29 06:55 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
> +                if (false) {
OK

2024-02-29 06:56 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            // Button to open the detailed search area
OK

2024-02-29 06:58 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            // page init
ok

2024-02-29 06:59 UTC, ivis-tsukioka commented on modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> +            let status_keep_flg = true
ok

2024-02-29 07:02 UTC, ivis-tsukioka approved these changes
すべての指摘に対して対応できていることを確認しました

2024-03-05 00:39 UTC, merged