HIROBA_MIG-1806
ivis-weko3-dev/weko pull request #227
Opened 2024-04-24 07:58 UTC by kanon-yoneji

HIROBA_MIG-1806
 get_billinginfo_from_metadata,handle_check_billing_fileメソッド追加

2024-05-08 10:08 UTC, asuzuki1 requested changes
レビューしました。処理は問題ないと思います。
1点（2か所）、docstringのスタイルについてコーディング規約に指定があるので、新規作成したメソッドについてはそちらに従った記法に修正お願いします。

2024-05-09 02:38 UTC, kanon-yoneji commented on modules/weko-search-ui/weko_search_ui/utils.py
> +    """
docstringを修正しました。

2024-05-09 02:38 UTC, kanon-yoneji commented on modules/weko-search-ui/weko_search_ui/utils.py
> +    """
docstringを修正しました。

2024-05-09 12:03 UTC, asuzuki1 requested changes
Args および Returns の引数・戻り値の記述形式がGoogleスタイルでないので修正お願いします。

2024-05-09 12:03 UTC, asuzuki1 commented on modules/weko-search-ui/weko_search_ui/utils.py
> +    """
Googleスタイルでは
　`metadata -- {dict} record metadata.`
は
　`metadata (dict): record metadata.`
という形式になると思いますので、`handle_check_billing_file`メソッドの方と併せて修正お願いします。

2024-05-09 12:03 UTC, asuzuki1 commented on modules/weko-search-ui/weko_search_ui/utils.py
> +    """
`get_billinginfo_from_metadata`メソッドでの指摘参照

2024-05-10 00:44 UTC, kanon-yoneji commented on modules/weko-search-ui/weko_search_ui/utils.py
> +    """
指摘箇所修正しました。

2024-05-10 00:44 UTC, kanon-yoneji commented on modules/weko-search-ui/weko_search_ui/utils.py
> +    """
指摘箇所修正しました。

2024-05-14 02:03 UTC, asuzuki1 approved these changes
@kanon-yoneji 
修正確認しました。指摘ありません。

2024-05-30 09:29 UTC, merged