NII_WEKO3-59 一括エクスポート処理の改善
ivis-weko3-dev/weko pull request #228
Opened 2024-04-25 07:45 UTC by ryoya-hayase

write_files_task, write_files メソッド追加
export_all, check_export_status, cancel_export, download, export_all_task, cancel_export_all, get_export_status メソッド修正
一括エクスポート html, js修正

2024-05-08 11:08 UTC, asuzuki1 requested changes
@ryoya-hayase 
2点コメント（要横展開）していますので、確認お願いします。

2024-05-08 11:08 UTC, asuzuki1 commented on modules/weko-search-ui/weko_search_ui/translations/en/LC_MESSAGES/messages.po
- 先頭が #~ のものはおそらくコメント扱いで認識されないと思われますので、コメント解除してください。
- .po ファイルをコンパイルして .mo ファイルを作成する必要があります。
  - 言語リソースは .mo を参照しているため、コンパイルしないと多言語化されません。
  - 多言語化の方法はteamsの夕会議事メモのノウハウのところに記載があったハズ。

上記2点は ja の方にも横展開してください。

2024-05-09 02:18 UTC, ryoya-hayase commented on modules/weko-search-ui/weko_search_ui/tasks.py
> +import json
指摘の通り修正しました。

2024-05-09 02:20 UTC, ryoya-hayase commented on modules/weko-search-ui/weko_search_ui/translations/en/LC_MESSAGES/messages.po
指摘の通り修正しました。
また、jaの方は相談した通り、msgstrの値を空文字としました。

2024-05-09 11:50 UTC, asuzuki1 approved these changes
修正確認しました。指摘ありません。

2024-05-23 05:02 UTC, asuzuki1 commented
テスト確認しました。指摘ありません。

2024-05-23 05:02 UTC, merged