NII_WEKO3-70 シボレスログイン後のリダイレクト対応
ivis-weko3-dev/weko pull request #230
Opened 2024-05-02 01:14 UTC by ryoya-hayase

set_next_session メソッド追加

2024-05-09 07:24 UTC, asuzuki1 requested changes
`@blueprint.before_request`だと同brueprint内のすべてのリクエスト時に実行されてしまいます。

シボレスログイン処理ではidp側でのログイン後、sp経由で`POST /shib/login`が呼び出されます。その後`GET /auto/login`か`GET /shib/login`に飛ぶようになっています。
`POST /shib/login`の処理を見る限りは次のリクエスト時に「next」のパラメータ指定が無いため、`GET /auto/login`および`GET /shib/login`が呼び出された際に `session['next']` はデフォルトの「`/`」で更新されてしまい、結果的にトップページへ遷移してしまうと思われます。

別の方法での実装を検討する必要がありそうです。

2024-05-10 02:35 UTC, ryoya-hayase commented
@asuzuki1 
相談した内容をもとに、実装方法を変更いたしました。

2024-05-14 02:20 UTC, asuzuki1 approved these changes
@ryoya-hayase 
確認しました。指摘ありません。

2024-05-23 05:15 UTC, asuzuki1 commented
テスト確認しました。指摘ありません。

2024-05-23 05:16 UTC, merged