NII_WEKO3-68 オープンアクセスファイルのダウンロード数の出力
ivis-weko3-dev/weko pull request #231
Opened 2024-05-07 01:13 UTC by ryoya-hayase

file-download-v1, aggr-file-download-v1 インデックス定義修正 ドキュメント登録・検索処理修正

2024-05-14 01:58 UTC, asuzuki1 requested changes
@ryoya-hayase 
レビューしました。2か所コメントしていますので確認お願いします。

2024-05-14 01:58 UTC, asuzuki1 commented on modules/weko-admin/weko_admin/translations/ja/LC_MESSAGES/messages.po
> +msgid "Open-Access No. Of Paid File Downloads"
同様のキーを en の方にも定義してください。
また、コンパイルしてmoファイルの作成もお願いします。

2024-05-14 01:58 UTC, asuzuki1 commented on modules/weko-records-ui/weko_records_ui/utils.py
> +
オープンアクセスの判定にはアイテムの所属インデックスの公開状態（ステータス・公開日）も考慮するようにしてください。

2024-05-14 05:41 UTC, ryoya-hayase commented on modules/weko-admin/weko_admin/translations/ja/LC_MESSAGES/messages.po
> +msgid "Open-Access No. Of Paid File Downloads"
ご指摘の通り、enフォルダのファイルにも同様のキーを追加し、
それぞれのmoファイルをコンパイルしてコミットしました。

2024-05-14 05:41 UTC, ryoya-hayase commented on modules/weko-records-ui/weko_records_ui/utils.py
> +
アイテムの公開判定の前に、所属するインデックスの公開状態を確認するよう修正しました。

2024-05-14 06:12 UTC, asuzuki1 approved these changes
@ryoya-hayase 
修正ありがとうございます。確認しました。
追加の指摘はありません。

2024-05-27 00:42 UTC, asuzuki1 approved these changes
テストレビュー済み。

2024-05-27 00:42 UTC, merged