V0.9.26 hiroba mig 1779
ivis-weko3-dev/weko pull request #234
Opened 2024-05-27 01:43 UTC by kanon-yoneji

2024-05-27 10:53 UTC, asuzuki1 requested changes
2件コメントしましたので確認お願いします。

2024-05-27 10:53 UTC, asuzuki1 commented on modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/body_contents.html
> +                                {%- set price = priceinfo.price|int -%}
税抜（=`include_tax`でない）価格が設定されている場合に税込表示されないのでは？
(`{%- if priceinfo.has_role and file.billing_file_permission -%}` の分岐自体不要？)

2024-05-27 10:53 UTC, asuzuki1 commented on modules/weko-records-ui/weko_records_ui/utils.py
> +        if user_flag and not sitelicense_flag and not p_file['accessrole'] == 'open_access':
「オープンアクセス」であるファイルの条件は `accessrole` が `'open_access'` である場合の他、`'open_date'` かつ 公開日を過ぎている場合もあります。

「3. [定型レポート]オープンアクセスファイルのダウンロード数の出力」の対応でアイテム（ファイル）がオープンアクセスかを判定するメソッドが追加されているので参考にしてください。
https://github.com/ivis-weko3-dev/weko/pull/231/files#diff-9001d018bfa90b92e143ea3eb1cd62a9d17ebd04c0fede4b1773b68db60bf136R208-R237

2024-05-28 01:08 UTC, kanon-yoneji commented on modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/body_contents.html
> +                                {%- set price = priceinfo.price|int -%}
分岐自体を削除しました。

2024-05-28 01:10 UTC, kanon-yoneji commented on modules/weko-records-ui/weko_records_ui/utils.py
> +        if user_flag and not sitelicense_flag and not p_file['accessrole'] == 'open_access':
add_billing_infoメソッドから呼び出している、check_file_download_permissionメソッド内においてオープンアクセス状態か判定した値を持っていたので、その値で判定をするよう修正しました。

2024-05-28 01:30 UTC, asuzuki1 approved these changes
確認しました。指摘ありません。

2024-05-30 09:29 UTC, merged