V0.9.26 hiroba mig 1788
ivis-weko3-dev/weko pull request #236
Opened 2024-05-27 11:17 UTC by kanon-yoneji

2024-05-28 01:16 UTC, asuzuki1 requested changes
@kanon-yoneji 
２件コメントありますので確認お願いします。

2024-05-28 01:16 UTC, asuzuki1 commented on modules/weko-admin/weko_admin/utils.py
> +    interface_name = WEKO_ADMIN_SITELICENSE_REPORT_INTERFACE_NAME
直接 .configをimportして設定値を読み込んでいますが、この記述だと instance.cfg で設定値のオーバーライドができず、値を変更する場合本番環境ではコンテナの再ビルドが必要となります。
理由が無い限りは、原則 `current_app.config['xxxxxxxxxx']` の記法で instance.cfg でオーバーライド可能にしておいてください。（今回修正した箇所で同様の部分があれば横展開してください）

2024-05-29 01:44 UTC, kanon-yoneji commented on modules/invenio-stats/invenio_stats/utils.py
> +            current_app.logger.debug(e)
error出力に修正しました。

2024-05-29 01:46 UTC, kanon-yoneji commented on modules/weko-admin/weko_admin/utils.py
> +    interface_name = WEKO_ADMIN_SITELICENSE_REPORT_INTERFACE_NAME
configのimportではなく、instance.cfgに設定値を設定して、current_appの記法に書き換えました。
instance.cfgで設定値を変更すると、変更された値が適用されます。

2024-05-29 02:32 UTC, asuzuki1 approved these changes
確認しました。指摘ありません。

2024-06-10 08:00 UTC, asuzuki1 approved these changes
単体テストに関して特に指摘ありません。

2024-06-10 08:02 UTC, merged