reindex and add index_id, is_open_access
ivis-weko3-dev/weko pull request #244
Opened 2024-06-25 04:26 UTC by kanon-yoneji

2024-06-25 08:42 UTC, asuzuki1 requested changes
@kanon-yoneji 
1件コメントありますのでご確認お願いします。

2024-06-25 08:42 UTC, asuzuki1 commented on tools/v0.9.26_hiroba_reindex.py
> +        stats_file_download_index=os.environ.get('SEARCH_INDEX_PREFIX', 'tenant1') + '-stats-file-download-000001'
各インデックス名末尾が「-000001」で固定されていますが、実際にはそれ以外も存在する可能性があります。
現在の設定では50GB単位でロールオーバーされるため、「-000002」等のインデックスに対しても同様の処理が行えるように考慮する必要があります。

なお、移行した環境では移行前のログが「000001～000009」に格納され、移行後の統計は「000010
～」に登録されるようになっています。

2024-06-26 01:28 UTC, asuzuki1 requested changes
@kanon-yoneji 
2件コメントつけましたのでご確認お願いします。
（内1つは懸念事項レベルの内容なので、そちらは修正不要かも。）

2024-06-26 01:28 UTC, asuzuki1 commented on tools/v0.9.26_hiroba_reindex.py
> +                    all_reindex_targets[key][index] = {'index':index,'alias_name':index + 'aliasname','file_path':'/file_preview/v6/file-preview-v1.json','refresh_interval':'5s'}
これだと 'alias_name' が「tenant1-stats-record-view-000001aliasname」のようになってしまう気がします。

サフィックスが「000001」でも「000010」でもエイリアスは「tenant1-stats-record-view」のようになってほしいので、`'alias_name': os.environ.get('SEARCH_INDEX_PREFIX', 'tenant1') + '-' + key` とかだとよさそうでしょうか？

2024-06-26 01:28 UTC, asuzuki1 commented on tools/v0.9.26_hiroba_reindex.py
> +                { "add" : { "index" : index, "alias" : alias_name } }
【懸念事項】
同一エイリアスのインデックスがある場合、古いインデックスは`"is_write_index": false` に、最新のインデックスのみ`"is_write_index": true`にしておく必要がある。
インデックス再作成するので、このツール内で再度設定しなければならないかもしれない。
ただし、`tools/update/fix_elasticsearch_aliases.py` にエイリアスを再設定するツールがあるようなので、今回のツール実行後に当該ツールを実行するようにすれば良いかもしれない。

2024-06-26 06:05 UTC, kanon-yoneji commented on tools/v0.9.26_hiroba_reindex.py
> +                { "add" : { "index" : index, "alias" : alias_name } }
同一エイリアスのインデックスがある場合、古いインデックスは"is_write_index": false に、最新のインデックスのみ"is_write_index": trueにする処理を追加しました。

2024-06-26 06:05 UTC, kanon-yoneji commented on tools/v0.9.26_hiroba_reindex.py
> +                    all_reindex_targets[key][index] = {'index':index,'alias_name':index + 'aliasname','file_path':'/file_preview/v6/file-preview-v1.json','refresh_interval':'5s'}
エイリアス名を修正しました。

2024-06-26 06:54 UTC, asuzuki1 approved these changes

2024-06-26 07:09 UTC, merged