W2023 21 feature/ticket 35018 35021 35022 35023
ivis-weko3-dev/weko pull request #83
Opened 2023-06-02 06:22 UTC by ayumijin

以下が一緒になってしまい申し訳ありません。
第１版です。
１.コンテンツ登録機能の拡張
２.代理投稿機能の拡張

2023-06-13 02:14 UTC, asuzuki1 requested changes
@ayumijin 
コード内にコメントつけましたので確認・修正お願いいたします。

2023-06-13 02:14 UTC, asuzuki1 commented on modules/weko-search-ui/weko_search_ui/utils.py
> +
デバッグコードは削除してコミットお願いします。

2023-06-13 02:14 UTC, asuzuki1 commented on modules/weko-workflow/weko_workflow/utils.py
> +    print('************rtn******** {}', rtn)
デバッグコードは削除してください。

2023-06-13 02:14 UTC, asuzuki1 commented on modules/weko-workflow/weko_workflow/views.py
> +    validate_guest_activity_token, get_contributors \
末尾のバックスラッシュは不要

2023-06-13 02:14 UTC, asuzuki1 commented on modules/weko-workflow/weko_workflow/views.py
> +    print(contributors)
デバッグコードは削除してください

2023-06-13 02:14 UTC, asuzuki1 commented on postgresql/ddl/spXX-UpdateItemMetadata.sql
未完成のため一旦削除お願いします。

2023-06-13 02:14 UTC, asuzuki1 commented on postgresql/ddl/spXX-UpdateItemType.sql
未完成のため一旦削除お願いします。

2023-06-13 02:14 UTC, asuzuki1 commented on postgresql/ddl/spXX-UpdateItemTypeProperty.sql
未完成のため一旦削除お願いします。

2023-06-13 02:14 UTC, asuzuki1 commented on postgresql/ddl/spXX-UpdateRecordsMetadata.sql
未完成のため一旦削除お願いします。

2023-06-13 02:14 UTC, asuzuki1 commented on postgresql/ddl/spXX_UpdateWorkflowActivity.sql
未完成のため一旦削除お願いします。

2023-06-15 01:12 UTC, ayumijin commented
競合を解消し、コミットしました。

2023-06-15 01:15 UTC, ayumijin commented on postgresql/ddl/spXX-UpdateItemMetadata.sql
削除しました。

2023-06-15 01:15 UTC, ayumijin commented on postgresql/ddl/spXX-UpdateItemType.sql
削除しました。

2023-06-15 01:16 UTC, ayumijin commented on postgresql/ddl/spXX-UpdateItemTypeProperty.sql
削除しました。

2023-06-15 01:16 UTC, ayumijin commented on postgresql/ddl/spXX-UpdateRecordsMetadata.sql
削除しました。

2023-06-15 01:16 UTC, ayumijin commented on postgresql/ddl/spXX_UpdateWorkflowActivity.sql
削除しました。

2023-06-15 01:17 UTC, ayumijin commented on modules/weko-deposit/weko_deposit/api.py
> +            print("******************************* record={}", record)
削除しました。

2023-06-15 01:17 UTC, ayumijin commented on modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/app.js
> +          $("#inputModal").html('Ownerは必ず選択してください。');
エラーメッセージを「Be sure to select an owner.」にしました。設計書も修正しました。

2023-06-15 01:41 UTC, ayumijin commented on modules/weko-workflow/weko_workflow/views.py
> +    print(contributors)
削除しました。

2023-06-15 01:42 UTC, ayumijin commented on modules/weko-workflow/weko_workflow/views.py
> +    validate_guest_activity_token, get_contributors \
削除しました。（エラーにならないのか・・・）

2023-06-15 01:42 UTC, ayumijin commented on modules/weko-workflow/weko_workflow/utils.py
> +    print('************rtn******** {}', rtn)
削除しました。

2023-06-15 01:44 UTC, ayumijin commented on modules/weko-search-ui/weko_search_ui/utils.py
> +
削除しました。

2023-06-15 01:50 UTC, ayumijin commented on modules/weko-search-ui/weko_search_ui/query.py
> +                #Q("match", weko_shared_ids&[user_id]) #Q("match", weko_shared_ids&[user_id]) ESカラム更新後これにする old Q("match", weko_shared_id=user_id)
# TODO ESカラム更新後以下のコメントを外す org. Q("match", weko_shared_id=user_id)
に変更しました。

2023-06-15 01:50 UTC, ayumijin commented on modules/weko-items-ui/weko_items_ui/views.py
> +                result['error'] = "ログインユーザーは削除できません。"
多言語対応しました。

2023-06-15 01:50 UTC, ayumijin commented on modules/weko-items-ui/weko_items_ui/views.py
> +        message = "ログインユーザーは削除できません。"
多言語対応しました。

2023-06-15 02:42 UTC, ayumijin commented on modules/weko-records-ui/weko_records_ui/static/js/weko_records_ui/detail.js
> +    return deferred;
すみません。マージミスしていました。修正しました。

2023-06-15 03:11 UTC, ayumijin commented
指摘事項対応内容は以下に移動しました。
https://github.com/ivis-weko3-dev/weko/pull/84

2023-06-15 03:11 UTC, closed without merging